Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,9 +9,12 @@ env:
   AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
   AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
   AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
+  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Docker Registry
+  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Docker Registry
   BUILD_NUMBER: ${{ github.run_id }}
   BUILD_NAME: ${{ github.repository }}
   GITHUB_WORKSPACE: ${{ github.workspace }}
+  GH_TOKEN: ${{ secrets.GH_TOKEN }}
   IMAGE_NAME: stanhoe/spring4shell:githubpush
   
 jobs:
@@ -49,7 +52,33 @@ jobs:
         docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
         docker pull registry.aquasec.com/scanner:2022.4
         docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2022.4 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --local $IMAGE_NAME --htmlfile /tmp/out.html --jsonfile /tmp/out.json > /dev/null
-    
+    - name: Push Docker image to repository
+      run: |
+        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
+        docker push $IMAGE_NAME
+    - name: Aqua Release Artifact 
+      run: |
+        export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+        if ! cat install.sh.checksum | sha256sum ; then
+        echo "install.sh checksum failed"
+        exit 1
+        fi
+        BINDIR="." sh install.sh
+        rm install.sh install.sh.checksum
+        ./billy generate \
+          --access-token "${{ secrets.GH_TOKEN }}" \
+          --aqua-key "${{ secrets.AQUA_KEY }}" \
+          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+          --cspm-url https://asia-1.api.cloudsploit.com \
+          --artifact-path $IMAGE_NAME 
+
+          # The docker image name:tag of the newly built image
+          # --artifact-path "my-image-name:${{ env.tag-version }}" 
+          # OR the path to the root folder of your project. I.e my-repo/my-app 
+          # --artifact-path "${{env.MY_APP_ROOT}}"
+          
     - uses: actions/upload-artifact@v3
       with:
         name: aqua-artifact
