Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,12 +37,13 @@ jobs:
           CSPM_URL: https://asia-1.api.cloudsploit.com
           
   build:
+    name: Build, Scan, and Push Docker image
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag $IMAGE_NAME
-    - name: Aqua Scanner
+    - name: Aqua Image Scanner
       run: |
         docker image ls 
         docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
@@ -53,3 +54,25 @@ jobs:
       with:
         name: aqua-artifact
         path: out.*
+    - name: Manifest Generation
+      run: |
+        export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+        if ! cat install.sh.checksum | sha256sum ; then
+        echo "install.sh checksum failed"
+        exit 1
+        fi
+        BINDIR="." sh install.sh
+        rm install.sh install.sh.checksum
+        ./billy generate \
+          --access-token "${{ secrets.GITHUB_TOKEN }}" \
+          --aqua-key "${{ secrets.AQUA_KEY }}" \
+          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+          --cspm-url https://asia-1.api.cloudsploit.com \
+          --artifact-path "$IMAGE_NAME" 
+
+          # The docker image name:tag of the newly built image
+          # --artifact-path "my-image-name:${{ env.tag-version }}" 
+          # OR the path to the root folder of your project. I.e my-repo/my-app 
+          # --artifact-path "${{env.MY_APP_ROOT}}"
